[package]
name = "gtk-rss-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.7.2", features = ["v4_12"] }
libadwaita = "*"
glib = "0.18.2"

[build-dependencies]
glib-build-tools = "0.18.0"

